---
title: "About"
output:
  html_document:
    toc_float: false
    includes:
      before_body: [include_header.html, include_header_navpage.html]
---

<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-F5HJ5VRY62"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-F5HJ5VRY62');
</script>

# About

Passionate about leveraging quantitative analysis to drive impactful insights in economics. Proficient in econometric modeling, harnessing the power of artificial intelligence and remote sensing for cutting-edge socioeconomic analysis. Committed to providing technical expertise that shapes policy-making decisions, my journey encompasses in-depth analyses, crafting compelling studies on socioeconomic phenomena, and executing impact evaluations across diverse interventions. Eager to perpetuate the fusion of data and policy for meaningful societal impact.

## Experience / Skills

Research • Econometrics • Machine Learning • Remote Sensing • Data Science / Critical Thinking • Problem Solving

## CV

<iframe class="scribd_iframe_embed" title="CV Osmar Bolivar(Jan2024)" src="https://www.scribd.com/embeds/703234342/content?start_page=1&view_mode=scroll&access_key=key-9U5w7WLAj7pgPwmUjCmO" tabindex="0" data-auto-height="true" data-aspect-ratio="0.7729220222793488" scrolling="no" width="100%" height="600" frameborder="0"></iframe>


